### ISSUE TITLE
SAMM - IEC62443-4-1 Mapping

### ISSUE THREAD

**Issue by maximbaele** [owaspsamm/samm-suite#51]
I have made a first pass at mapping IEC62443-4-1 to SAMM. 
Mapping is done on a per-stream-basis due to the difference in how IEC focuses more on documents and deliverables and SAMM focuses more on process

[SAMM IEC62443.xlsx](https://github.com/owaspsamm/samm-suite/files/14736811/SAMM.IEC62443.xlsx)

**Comment by aramhovsepyan** [comment]
- SM-11 seems like a requirements verification issue rather than defect management. 
- SM-13 is also linked to G-SM-B I think (continuously improving SDL based on metrics)
- SD-2 is D-TA-B and D-SA-A for sure (why the question mark)
- SI-2 is about coding standards which belongs to G-PC-A
- SVV-1 is about functional testing of security requirements and should be V-RT-A and V-RT-B (both). V-AA-B is essentially about threat model verification
- SVV-2 should also include V-AA-B
- SVV-3 should include V-RT-B (fuzzing, stress testing
- SVV-4 I disagree with V-RT-B. Only V-ST-B fits here.
- DM-1 seems more defect related to me than incident response. I-DM-A
- DM-4 perhaps I-DM-B (addressing reported defects). Does seem somewhat related to D-SR-B but that's a weak link
- DM-6 definitely also I-DM-B (improving defect management process). 
- SUM-1 and SUM-2 should also include O-OM-B (operational management)
- SUM-3, SUM-4 and SUM-5 also link to O-OM-B
- SG-1 and SG-2 - I'd argue that these are fancy activities that are largely related to hardening, i.e., to O-EM-A. It's a weaker link and requires some mental gymnastics.
